[[redirects]]
  from = "http://yuno.ryu-s.jp/*"
  to   = "https://yuno.ryu-s.jp/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "http://www.yuno.ryu-s.jp/*"
  to   = "https://yuno.ryu-s.jp/:splat"
  status = 301
  force  = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy   = "upgrade-insecure-requests"
    X-Frame-Options           = "SAMEORIGIN"
    X-Content-Type-Options    = "nosniff"
    Referrer-Policy           = "strict-origin-when-cross-origin"
